version: "3.9"
services:
  web:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8080}
    volumes:
      - ./:/app
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT:-8080}/_stcore/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

